### PR TITLE
Update: new endpoint for updub / downdub

### PR DESCRIPTION
**Pull request by thedark1337**
Developer of Dubtrack recently announced on Slack that the endpoint has been updated and an API limit has been added.

### CODE REVIEW

**Comment by anjanms** [comment]
Thanks for the heads up.

Did they say anything about how the API limit works? How it responds and about how long it lasts?
I can find out myself, but I'd prefer not to spam their servers if I can help it.

**Comment by thedark1337** [comment]
For now the limit is set high at a 10 but later on it might change. After 10 requests on one song it returns error 429. I'll update my commit to change to what you suggested

**Comment by thedark1337** [comment]
Amended the commit to your suggestions

**Comment by anjanms** [comment]
Ah, okay. It's to stop people from repeatedly toggling their vote. That shouldn't be a problem.

Thanks!

**Pull request merged**
