### PR TITLE
add setrole

### PR DESCRIPTION
**Pull request by Fuechschen**
Well, it's just making bots capable of setting roles...

### CODE REVIEW

**Comment by anjanms** [comment]
Hey, thanks for submitting another PR. Sorry it's taken me so long to review this.

A couple things with this one.
- Check if the bot has 'set-roles' permission.
- Use role ids instead of 1 - 5, just check that it's defined in ```/lib/data/roles.js``` before going further.
- Use ```%ROLEID%``` in the endpoint url and just replace it.

I'll probably combine set and unset into one method, unless you want to.

Thanks again. :smiley:

**Comment by Fuechschen** [comment]
So, i hope i changed it right...

I also added changed the way, moderateRemoveDJ works (https://github.com/dubtrack/www-dubtrack-fm/issues/164). (If you just want to remove the specific song, use moderateRemoveSong)

**Comment by anjanms** [comment]
You've got the right idea. But looking at the diff I see three issues.

The permission is 'set-roles' (plural), you have 'set-role'.
The indexOf check won't work as ```roles``` isn't an array. It should just be an undefined check. (```roles[role] === undefined```)

Also it looks like you accidentally deleted the media methods, please re-add those.

moderateRemoveDJ and moderateRemoveSong look good. :+1: 

Thanks

**Comment by Fuechschen** [comment]
So, i hope i haven't forgot anything...
Yeah, sorry for that, seems like i totally switched off my brain that day...

**Comment by anjanms** [comment]
Perfect. :+1: 

You'll see an update with this soon.

**Pull request merged**
